/*
*   JSL D-NOW LIB for serial port  *
*   Author: Shengjia.zhu           *
*   Date: 2012/10/15               *
*/

/*
  This file is User Header of D-Now Lib
  Do not edit this file!!
*/

#ifndef __SERIAL_API__H__
#define __SERIAL_API__H_

#define serial_init( port_id, baud_rate ) _serial_init_##port_id##_##baud_rate()
#define setup_serial_isr_op(port_id,fun)  _setup_serial_isr_##port_id(fun)

u16 _serial_init_0_1200();
u16 _serial_init_0_2400();
u16 _serial_init_0_4800();
u16 _serial_init_0_9600();
u16 _serial_init_0_19200();
u16 _serial_init_0_38400();
u16 _serial_init_0_57600();
u16 _serial_init_0_115200();

u16 _serial_init_1_1200();
u16 _serial_init_1_2400();
u16 _serial_init_1_4800();
u16 _serial_init_1_9600();
u16 _serial_init_1_19200();
u16 _serial_init_1_38400();
u16 _serial_init_1_57600();
u16 _serial_init_1_115200();

u16 _serial_init_2_1200();
u16 _serial_init_2_2400();
u16 _serial_init_2_4800();
u16 _serial_init_2_9600();
u16 _serial_init_2_19200();
u16 _serial_init_2_38400();
u16 _serial_init_2_57600();
u16 _serial_init_2_115200();

u16 _serial_init_3_1200();
u16 _serial_init_3_2400();
u16 _serial_init_3_4800();
u16 _serial_init_3_9600();
u16 _serial_init_3_19200();
u16 _serial_init_3_38400();
u16 _serial_init_3_57600();
u16 _serial_init_3_115200();


void _setup_serial_isr_0( pcb call_back_fun );
void _setup_serial_isr_1( pcb call_back_fun );
void _setup_serial_isr_2( pcb call_back_fun );
void _setup_serial_isr_3( pcb call_back_fun );

//void serial_deinit( u8 port_id );
void serial_send_byte( u16 handle, u8 val );
void serial_send_buf( u16 handle, uchar *buf, u16 len );
void serial_send_str( u16 handle, uchar *str );

u8 serial_receive_byte( u16 handle );
u16 serial_receive_buf( u16 handle, uchar *buf, u16 len );
u16 serial_receive_str( u16 handle, uchar *str );

//with wait timeout API
u16 serial_receive_buf_wt( u16 handle, uchar *buf, u16 len, u16 timeout );
u16 serial_receive_str_wt( u16 handle, uchar *str, u16 timeout );

void serial_rx( u8 port_id );
void serial_deinit( u16 handle );
void setup_serial_isr( u16 handle, pcb call_back_fun );

#endif //__SERIAL_API__H__