/*
*   JSL D-NOW LIB for libtimer  *
*   Author: Shengjia.zhu           *
*   Date: Nov 19, 2012               *
*/

//            /*/*/*/*/*         /*/*/*　　　　　　　/*/*/*/*/*/*/*/*
//                  /*/*        /*/*/*　　　　　　　/*/*/*
//                  /*/*        /*/*/*　　　　　　　/*/*/*
//                  /*/*        /*/*/*　　　　　　　/*/*/*/*/*/*/*/*
//      /*/*/*      /*/*        /*/*/*　　　　　　　　　　　　　/*/*
//      /*/*/*      /*/*        /*/*/*　　　　　　　　　　　　　/*/*
//       /*/*/*/*/*/*/*        /*/*/*/*/*/*/*/*　　/*/*/*/*/*/*/*/*

/*
  This file is User Header of D-Now Lib
  Do not edit this file!!
*/


#ifndef JLS_TIMER_API_H_
#define JLS_TIMER_API_H_
#include "jls_common_api.h"

/*******************  Timer0 ************************/
/* monopulse output pin define */

//P1
#define T0_MONO_PULSE_OUT_P1_1		0
#define T0_MONO_PULSE_OUT_P1_2		1
#define T0_MONO_PULSE_OUT_P1_3		2
#define T0_MONO_PULSE_OUT_P1_4		3
#define T0_MONO_PULSE_OUT_P1_5		4
//P8
#define T0_MONO_PULSE_OUT_P8_0		5
#define T0_MONO_PULSE_OUT_P8_1		6
#define T0_MONO_PULSE_OUT_P8_2		7
#define T0_MONO_PULSE_OUT_P8_3		8
#define T0_MONO_PULSE_OUT_P8_4		9

/* PWM output pin define */

//P1
#define T0_PWM_OUT_P1_2		1
#define T0_PWM_OUT_P1_3		2
#define T0_PWM_OUT_P1_4		3
#define T0_PWM_OUT_P1_5		4
//P8
#define T0_PWM_OUT_P8_1		6
#define T0_PWM_OUT_P8_2		7
#define T0_PWM_OUT_P8_3		8
#define T0_PWM_OUT_P8_4		9


/*******************  Timer1 ************************/

/* monopulse output pin define */


#define T1_MONO_PULSE_OUT_P8_5		0
#define T1_MONO_PULSE_OUT_P8_6		1
#define T1_MONO_PULSE_OUT_P7_3		2

#define T1_MONO_PULSE_OUT_P2_1		3
#define T1_MONO_PULSE_OUT_P2_2		4
#define T1_MONO_PULSE_OUT_P2_3		5


/* PWM output pin define */

#define T1_PWM_OUT_P8_6		1
#define T1_PWM_OUT_P7_3		2

#define T1_PWM_OUT_P2_2		4
#define T1_PWM_OUT_P2_3		5

/*******************  Timer2 ************************/

/* monopulse output pin define */


#define T2_MONO_PULSE_OUT_P4_0		0
#define T2_MONO_PULSE_OUT_P4_1		1
#define T2_MONO_PULSE_OUT_P4_2		2
#define T2_MONO_PULSE_OUT_P4_3		3
#define T2_MONO_PULSE_OUT_P4_4		4
#define T2_MONO_PULSE_OUT_P4_5		5
#define T2_MONO_PULSE_OUT_P4_6		6



/* PWM output pin define */

#define T2_PWM_OUT_P4_1		1
#define T2_PWM_OUT_P4_2		2
#define T2_PWM_OUT_P4_3		3
#define T2_PWM_OUT_P4_4		4
#define T2_PWM_OUT_P4_5		5
#define T2_PWM_OUT_P4_6		6



void timer0_clear();
void timer0_start();
void timer0_stop();
u16 timer0_read_val();
void timer0_set_task( u32 us,  vcb call_back_fun );

void timer0_task_list_init( u32 period );
void timer0_add_list_task( u32 time_val, vcb call_back_fun );
void timer0_mono_pulse( u8 out_pin, u32 keep_time, boolen steady_state );

void timer0_pwm_init( u32 period );
void timer0_pwm_out( u8 out_pin, float duty_cycle );

void timer0_deadzone_pwm_init(  u32 period  );
void timer0_deadzone_pwm_out( u8 out_pin1, float duty_cycle1, u8 out_pin2, float duty_cycle2, u32 deadzone_time );

void timer0_phaseshift_squarewave_init(  u32 period  );
void timer0_phaseshift_squarewave_out( u8 out, u16 phase );


void timer1_clear();
void timer1_start();
void timer1_stop();
u16 timer1_read_val();
void timer1_set_task( u32 us,  vcb call_back_fun );

void timer1_task_list_init( u32 period );
void timer1_add_list_task( u32 time_val, vcb call_back_fun );
void timer1_mono_pulse( u8 out_pin, u32 keep_time, boolen steady_state );

void timer1_pwm_init( u32 period );
void timer1_pwm_out( u8 out_pin, float duty_cycle );

void timer1_deadzone_pwm_init(  u32 period  );
void timer1_deadzone_pwm_out( u8 out_pin1, float duty_cycle1, u8 out_pin2, float duty_cycle2, u32 deadzone_time );

void timer1_phaseshift_squarewave_init(  u32 period  );
void timer1_phaseshift_squarewave_out( u8 out, u16 phase );

void timer2_clear();
void timer2_start();
void timer2_stop();
u16 timer2_read_val();
void timer2_set_task( u32 us,  vcb call_back_fun );

void timer2_task_list_init( u32 period );
void timer2_add_list_task( u32 time_val, vcb call_back_fun );
void timer2_mono_pulse( u8 out_pin, u32 keep_time, boolen steady_state );

void timer2_pwm_init( u32 period );
void timer2_pwm_out( u8 out_pin, float duty_cycle );

void timer2_deadzone_pwm_init(  u32 period  );
void timer2_deadzone_pwm_out( u8 out_pin1, float duty_cycle1, u8 out_pin2, float duty_cycle2, u32 deadzone_time );

void timer2_phaseshift_squarewave_init(  u32 period  );
void timer2_phaseshift_squarewave_out( u8 out, u16 phase );
#endif /* JLS_TIMER_API_H_ */
