/*
*   JSL D-NOW LIB for serial port  *
*   Author: Shengjia.zhu           *
*   Date: 2012/10/15               *
*/

/*
  This file is User Header of D-Now Lib
  Do not edit this file!!
*/

#ifndef __SERIAL_API__H__
#define __SERIAL_API__H_
#include "jls_common.h"
#define log_serial_init( port_id, baud_rate ) _log_serial_init_##port_id##_##baud_rate()





//void log_serial_deinit( u8 port_id );
void log_serial_send_byte( u16 handle, u8 val );

u8 log_serial_receive_byte( u16 handle );


#endif //__SERIAL_API__H__
